
services:
  # PHP-FPM untuk menjalankan aplikasi Laravel
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - app_network
    environment:
      - PHP_DATE_TIMEZONE=Asia/Jakarta
    build:
      context: .
      dockerfile: Dockerfile

  # Nginx untuk proxy ke PHP-FPM
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - app

  # Database MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: laravelku
      MYSQL_USER: root
      MYSQL_PASSWORD: pass1
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
